# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: pokedex-api

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js 
    includeModules: true

functions:
  listPokemons:
    handler: pokemons/PokemonsController.list
    events:
      - http:
          path: pokemons
          method: get
          cors: true
  readPokemon:
    handler: pokemons/PokemonsController.read
    events:
      - http:
          path: pokemons/{id}
          method: get
          cors: true
